# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: "${APP}-volsync"
stringData:
    RESTIC_REPOSITORY: "/mnt/default/Volsync/${APP}"
    RESTIC_PASSWORD: p
