---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
  namespace: media
data:
  # URLS
  IMMICH_SERVER_URL: http://immich-server.media.svc.cluster.local:2283
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.media.svc.cluster.local:3003
  PUBLIC_IMMICH_SERVER_URL: https://photos.${SECRET_DOMAIN}
  # SETTINGS
  IMMICH_LOG_LEVEL: log
  UPLOAD_LOCATION: /usr/src/app/upload
  # REDIS
  REDIS_HOSTNAME: immich-redis.media.svc.cluster.local
  REDIS_DBINDEX: "1"
  REDIS_PORT: "6379"
