apiVersion: v1
kind: Secret
metadata:
  name: immich-db-secret
  namespace: media
type: Opaque
stringData:
  DB_USERNAME: ENC[AES256_GCM,data:IlFPdEsN,iv:01xVk2DWZC5jzQXbx7A/K4LVGwipTiMCHtuDl5//9B4=,tag:OTuaRgyLQ3sh/ira2TNZow==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:2K1F/ItN,iv:3D/PctDQxE7neVEJ4nHpJ3SH0i5Di9JQDdfL3oGVk2I=,tag:nhv76pA9e3OizsBxoko1dg==,type:str]
sops:
  age:
    - recipient: age1pguzgl6ueghhdzlzwelhl9asavxnr9jytr82mcarhswf0gw39gssvhcccm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWUpWdGhqbWliTEV2N2FG
        Q25ZcDBIUDNvV0pPU04xdHRwcjYzL0ZrOGdjCmNMd0JuQlZsVVNnTVNlUlNRMHNU
        Wis1dk9kMVU5c2R1cnFRZWNpVUFoL3MKLS0tIC9peFZuUUFraWlYKzBGUGx6aysx
        eFV2ZjJiODZlZ0tLRTBOLy9IclpEcjAKnWNdR5mndOi61zU3WutA0tmVMHq8boPw
        36Qn72Ez18ZgGjUtUcTzGSmcD2b1XR8K4rOsfcI+z1T21dUEf5D+Zw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T11:18:01Z"
  mac: ENC[AES256_GCM,data:xWGTswtQb9+Xgnoc2txlplN2nZnQSv2AFTFgaKjTJZ5c7Ls8X5o95JecA1q58bWjUM6pWf/KKffE7eGPNvZwZIG3RTHC9WBsS8i7u5w38b/nHKqr1ljnF9UBLL61ilu2eT4HXJw2+TmDda/PBB8ebzXznndGQUnw0r0Z3ZFXYaE=,iv:zuUT/qU/iggM5AUnAX2MOhRK3Cq5UdLtTstQLxgzyFM=,tag:Vxu+wIhkq+WT+mt042yqlw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
