apiVersion: v1
kind: Secret
metadata:
  name: immich-db-secret
  namespace: databases
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:T1X80Ezd,iv:Fqty2RPdhbCnp1YUnhV00GBccXRxRY/OQNO/e0eJ8S8=,tag:ZYSgZHuWnvKUdv2bAYcw3A==,type:str]
  password: ENC[AES256_GCM,data:vehKwps/,iv:bhKiC4wYLT9w4BWS7zz3iOZevsEP2il5066W4rp7PBU=,tag:H+VmwHwBVlxiS52LgfkS3g==,type:str]
sops:
  age:
    - recipient: age1pguzgl6ueghhdzlzwelhl9asavxnr9jytr82mcarhswf0gw39gssvhcccm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVmFxMjZwTWJsWjg0VUdr
        VnJrZU1TSzlhSzNxcmtwZE04OFcwWk5WRkdjCnhUTnJQbVN2VThPSUFtTXJIQTIr
        bkVzc1ZCTjBTTW9OOWdicDhsQllFcjgKLS0tIEJSYUdhVm12WVhCSDBQVURPMG55
        WU1sK0Q1bkVmbFZwWHdVU1h3d0wza1UKimZiphUbD/kYIbq9qLIoRyfzqbr7t1wU
        cLTFt+d07f0UV3Jy0eX7tjWBXQYnDTnFH4B9/LR4aXTxB2g0o40zSQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T11:18:01Z"
  mac: ENC[AES256_GCM,data:a4LqWEYNVIY/ftQLTyB0gM9CgobuEPcFybzLdoooahY5TYXG8Hn5e1dnUKzkGE/nNqBsqb4BtIPA7GZ/g/xsKfvryS5UZ+UsufVULeZYL9s+v941i7Vq/4oAL+9fT5nkh6v8+IbYs3e7i66d4VUEGUO8ChRfFhQEekJRFXdgHb4=,iv:t8wdJ5yTQuA+XZsxY7fnSxoR8/Kvbk7R0OX9dn54aV0=,tag:C23ccOnkkzf8YqBxUshFdw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
